title: FRAMEWORK FOR NETWORK COVERT CHANNELS
owner:
  name: Katharina
  copyright: 2023
settings:
  # global settings for the simulation
  # Quit after adjustable period of time [sec] or by 0, quit by completion of the message transfer
  time_quit: 0
  # a name for the simulation - don't use slashes or backslashes
  name: "coap-test-simulation"
protocols:
  # Choose between "OPCUA", "MODBUS", "S7COMM", "MQTT", "CoAP"
  CoAP:
    # Time intervals between retransmissions/reconnections/resets [sec]
    time_interval: 5
    client:
      host: coap-client
      path: coap/client-udp # the path to the Dockerfile
      image: null # if an external image should be used (not yet supported)
      instances: 10 # how often should the non-malicious client spawn
    server:
      host: server
      port: 5683
      internal: true
      image: null
      path: coap/server
      healthcheck: "nc -z -v localhost 5683"
    channels:
      PT12:
        exploited_clients: 0  # how many further clients should be used for the channel
        path: coap/pt12-retransmission
        image: null
        # Choose the Covert Message
        covert_str: this is my secret message
      PT15:
        exploited_clients: 0 # how many further clients should be used for the channel
        path: coap/pt15-reconnect
        image: null
        covert_str: my little secret message
        covert_file: null
      PT16:
        exploited_clients: 4 # how many further clients should be used for the channel
        path: coap/pt16-reset
        image: null
        covert_str: null
        covert_file: /home/user/payload.bin



